[[plugins]]
 repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = "nathanaelkane/vim-indent-guides"

[[plugins]]
repo = "thinca/vim-quickrun"

[[plugins]]
repo = "nathanaelkane/vim-indent-guides"

