[[plugins]]
repo   = 'Shougo/unite.vim'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = "davidhalter/jedi-vim"
depends = ['Shougo/neocomplete.vim']
on_ft = ['python']
hook_add = '''
    " jedi-vim and neocomplete (start) ----------------------------------------
    " docstringは表示しな
    autocmd FileType python setlocal completeopt-=preview
    "
    autocmd FileType python setlocal omnifunc=jedi#completions
    let g:jedi#completions_enabled = 0
    let g:jedi#auto_vim_configuration = 0
    let g:jedi#show_call_signatures = 0
    let g:jedi#auto_initialization    = 0
    let g:jedi#popup_select_first     = 0
    if !exists('g:neocomplete#force_omni_input_patterns')
        let g:neocomplete#force_omni_input_patterns = {}
    endif
    let g:neocomplete#force_omni_input_patterns.python = '\h\w*\|[^. \t]\.\w*'
    " jedi-vim and neocomplete (end) ----------------------------------------
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
