[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = "thinca/vim-quickrun"

[[plugins]]
repo = "nathanaelkane/vim-indent-guides"

[[plugins]]
repo = "kana/vim-smartinput"

[[plugins]]
repo = "cohama/vim-smartinput-endwise"

[[plugins]]
repo = "tomasr/molokai"

[[plugins]]
repo = "w0rp/ale"

[[plugins]]
repo = "tpope/vim-fugitive"
